version: '3.8'

services:
  batch-tracer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: batch-tracer
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EXTERNAL_API_URL=http://test-dev.api-eprod-solutions.com:9000/trace/orders
    networks:
      - app-network
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      # Uncomment the following lines if you have SSL certificates
      # - ./ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      # - ./ssl/private.key:/etc/nginx/ssl/private.key
    depends_on:
      - batch-tracer
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge